# Memory - ограничиваем BE
be_process_limit = 2147483648
mem_limit = 2147483648

# Network
priority_networks = 172.20.0.0/24

# Ports  
be_port = 9060
webserver_port = 8040
heartbeat_service_port = 9050
brpc_port = 8060

# Storage
storage_root_path = /opt/apache-doris/be/storage
priority_networks = 172.20.0.0/24
