table_name: lnk_shipment_warehouse
table_type: link
kafka_topic: logistics_service.public.shipments
source_system: logistics_service
hub_keys:
  hub_shipment_bk: shipment_external_id
  hub_warehouse_bk: origin_warehouse_code
